services:
  - type: web
    name: ghl-oauth-api
    runtime: node
    rootDir: .
    buildCommand: |
      set -e
      echo "=== STEP 1: Installing root dependencies ==="
      npm install
      echo ""
      echo "=== STEP 2: Current directory ==="
      pwd
      ls -la | head -15
      echo ""
      echo "=== STEP 3: Building frontend (this may take a few minutes) ==="
      echo "Current directory before build: $(pwd)"
      echo "Checking if src directory exists:"
      ls -la src/ | head -5 || echo "src directory not found"
      echo ""
      echo "Running npm run build..."
      npm run build 2>&1 | tee build-output.log || {
        echo "❌ Build failed! Checking for errors..."
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Build output (last 50 lines):"
        tail -50 build-output.log 2>/dev/null || echo "No build output log found"
        exit 1
      }
      echo ""
      echo "Build command completed. Checking output..."
      tail -20 build-output.log 2>/dev/null || echo "No build log to review"
      echo ""
      echo "=== STEP 4: Verifying build output ==="
      if [ ! -d "dist" ]; then
        echo "❌ CRITICAL: dist folder was not created!"
        echo "Directory contents after build:"
        ls -la
        exit 1
      fi
      if [ ! -f "dist/index.html" ]; then
        echo "❌ CRITICAL: dist/index.html not found!"
        echo "Dist contents:"
        ls -la dist/ || echo "dist directory doesn't exist"
        exit 1
      fi
      echo "✅ Build verification passed"
      echo "Dist folder size: $(du -sh dist | cut -f1)"
      echo "Dist contents preview:"
      ls -la dist/ | head -10
      echo ""
      echo "=== STEP 5: Ensuring dist persists (creating marker) ==="
      touch dist/.render-build-complete
      echo "$(date)" > dist/.render-build-timestamp
      echo ""
      echo "=== STEP 6: Installing server dependencies ==="
      cd server && npm install
    startCommand: cd server && node ghl-express-api.js
    envVars:
      # NOTE: Set these in Render Dashboard Environment tab - NEVER commit secrets here!
      # - key: GHL_CLIENT_ID
      #   value: YOUR_CLIENT_ID
      # - key: GHL_CLIENT_SECRET
      #   value: YOUR_CLIENT_SECRET
      # - key: GHL_SHARED_SECRET
      #   value: YOUR_SHARED_SECRET
      - key: GHL_REDIRECT_URI
        value: https://ghlvoiceai.captureclient.com/auth/callback
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

