services:
  - type: web
    name: ghl-oauth-api
    runtime: node
    buildCommand: |
      set -e
      echo "=== Building Application ==="
      echo "Working directory: $(pwd)"
      echo "Node version: $(node -v)"
      echo ""
      echo "=== Installing root dependencies ==="
      npm ci
      echo ""
      echo "=== Building frontend with Vite ==="
      npm run build
      echo ""
      echo "=== Verifying build output ==="
      if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
        echo "❌ CRITICAL: dist/index.html NOT found!"
        echo "Dist contents:"
        ls -la dist/ 2>/dev/null || echo "dist directory does not exist"
        exit 1
      fi
      echo "✅ Build complete! dist/index.html exists"
      echo ""
      echo "=== Installing server dependencies ==="
      cd server && npm ci
    startCommand: node server/ghl-express-api.js
    envVars:
      # NOTE: Set these in Render Dashboard Environment tab - NEVER commit secrets here!
      # - key: GHL_CLIENT_ID
      #   value: YOUR_CLIENT_ID
      # - key: GHL_CLIENT_SECRET
      #   value: YOUR_CLIENT_SECRET
      # - key: GHL_SHARED_SECRET
      #   value: YOUR_SHARED_SECRET
      - key: NODE_VERSION
        value: "20.17.0"
      - key: GHL_REDIRECT_URI
        value: https://ghlvoiceai.captureclient.com/auth/callback
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

