services:
  - type: web
    name: ghl-oauth-api
    runtime: node
    buildCommand: |
      set -e
      echo "=== STEP 1: Pre-build verification ==="
      echo "Current directory: $(pwd)"
      echo "Node version: $(node -v)"
      echo "NPM version: $(npm -v)"
      echo ""
      echo "Checking required files:"
      test -f package.json && echo "✅ package.json found" || (echo "❌ package.json missing!" && exit 1)
      test -f vite.config.ts && echo "✅ vite.config.ts found" || (echo "❌ vite.config.ts missing!" && exit 1)
      test -d src && echo "✅ src directory found" || (echo "❌ src directory missing!" && exit 1)
      echo ""
      echo "=== STEP 2: Installing root dependencies ==="
      npm install --production=false || {
        echo "❌ npm install failed!"
        exit 1
      }
      echo ""
      echo "=== STEP 3: Building frontend with CI build script ==="
      echo "Working directory: $(pwd)"
      echo "Using npm run build (calls scripts/ci-build.js with multi-method fallback)"
      echo ""
      # The ci-build.js script handles permissions, multiple build methods, and verification
      npm run build 2>&1 || {
        echo ""
        echo "❌ Build failed! Check logs above for details."
        exit 1
      }
      echo ""
      echo "=== STEP 4: Installing server dependencies ==="
      cd server && npm install
    startCommand: cd server && node ghl-express-api.js
    envVars:
      # NOTE: Set these in Render Dashboard Environment tab - NEVER commit secrets here!
      # - key: GHL_CLIENT_ID
      #   value: YOUR_CLIENT_ID
      # - key: GHL_CLIENT_SECRET
      #   value: YOUR_CLIENT_SECRET
      # - key: GHL_SHARED_SECRET
      #   value: YOUR_SHARED_SECRET
      - key: GHL_REDIRECT_URI
        value: https://ghlvoiceai.captureclient.com/auth/callback
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

