services:
  - type: web
    name: ghlvoiceai
    env: node
    rootDir: .
    buildCommand: |
      npm ci
      npm run build
    startCommand: |
      cd server
      node ghl-express-api.js
    envVars:
      # NOTE: Set these in Render Dashboard Environment tab - NEVER commit secrets here!
      # - key: GHL_CLIENT_ID
      #   value: YOUR_CLIENT_ID
      # - key: GHL_CLIENT_SECRET
      #   value: YOUR_CLIENT_SECRET
      # - key: GHL_SHARED_SECRET
      #   value: YOUR_SHARED_SECRET
      - key: NODE_VERSION
        value: "20.17.0"
      - key: FRONTEND_DIST_PATH
        value: /opt/render/project/dist
      - key: GHL_REDIRECT_URI
        value: https://ghlvoiceai.captureclient.com/auth/callback
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

